sudo: false
language: python
python:
- '2.7.12'
- '3.6'
install: python setup.py install
script:
- ./run_tests.sh
- pip install coveralls; coveralls
notifications:
  slack:
    secure: ncwwNPmHdvqwirYMz6XaCb7pVIed3jE0ejzeOMx+Ev5hqg7i0vKtyFLTdLC3uW99gjVtLVb0YAsy1zGXQGDrSJqtWC7mCk8bsVkeMGPcTJM1OiZ/xR+PzgIySUJty8oJCvfjoWXczO/nlij1AYPi89CsOlRr0Nvx92WyMNcDUyGZn4U5B+bHi/qHc32Nq5pnT9UUxo+yz2tBTLNyIziE6SRNoncUBxI/hALw+iFRbtuKoXcGnnuv24s0mVqOQ0BRfZjhYsEGcZ0B/yHhdayQPDrhGLV1Ry5O4ZElarWthpRrD+R34YHczsOmchnhN7qR2LlrH7mGwE+dO7vCza8XCh0BKYWL0Vs0Mc4VqgxltihkThlm5Yo1OJAAQi6PuOOMiFR7Q4inZX9NZ9Ub9JtvyZVgimo6TfCGBAsrBIMjAMMypbTrVpSsU8rMu04r2x1/P8Af/c9NnjpiHTXUBJBRE19cv9hO0HYa1QJCQTVMYm4mCCHxukUoA4hjSh2aLG8oHsG0PlbfrTTqnNqTbWM75p4izXqBIyBmo0vyrjuw11c+jFwZJH86aSFkhF1x4ycNlTWAOtmWSm6+lfyHTurHPNVLfA3cJ6JtUMr63wQ77Fw8zoUrNsjPtIvygxZLVCchOd2ck+Pw0pIfIPjOHyp7sZ7bwHjGV7N1vviw6xlWuK8=
